/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import newtonraphson.NewtonRaphsonFormula;


/**
 *
 * @author Core i5
 */
public class Interface extends javax.swing.JFrame {
NewtonRaphsonFormula nrf ;
    /**
     * Creates new form Interface
     */
    public Interface(NewtonRaphsonFormula nrf) {
        initComponents();
        this.nrf = nrf;
        Perform per = new Perform();
        Button.addActionListener(per);
        
        this.Table.setModel(new AbstractTableModel() {

            @Override
            public int getRowCount() {
                return nrf.getlistsize();
            }

            @Override
            public int getColumnCount() {
                return 4;
            }

            public String getColumnName(int ColumnIndex) {
                switch (ColumnIndex) {

                    case 0:
                        return "Numero";

                    case 1:
                        return "Margen Error";
                    case 2:
                        return "Raiz";
                    case 3:
                        return "# Interacciones";
                }

                return "";
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
               
                switch (columnIndex) {
                    case 0:
                        return nrf.getlist2().get(rowIndex);
                    case 1:
                        return TextField2.getText().trim();
                    case 2:
                        return nrf.getlist().get(rowIndex);
                    case 3:
                        return nrf.getlist3().get(rowIndex);
                }
                return "";
            }
        });

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField1 = new javax.swing.JTextField();
        TextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        TextField3 = new javax.swing.JTextField();
        Label4 = new javax.swing.JLabel();
        Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField2ActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Margen Error", "Raiz", "# Iteracciones"
            }
        ));
        jScrollPane1.setViewportView(Table);

        Label1.setText("Numero X :");

        Label2.setText("Margen de Error :");

        Label3.setText("# Iteracciones :");

        Label4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        Label4.setText("Newton Raphson");

        Button.setText("Enter");
        Button.setToolTipText("haga un segundo click para borrar");

        jLabel1.setText("Total Interacciones :");

        total.setEditable(false);
        total.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label4)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label3)
                            .addComponent(Label1)
                            .addComponent(Label2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(TextField2)
                            .addComponent(TextField3))
                        .addGap(46, 46, 46)
                        .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label4)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label2)
                    .addComponent(Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label3)
                    .addComponent(TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JTextField TextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

 public class Perform implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
          if (nrf.getlist().isEmpty()) { try {
                double Numero =  Double.parseDouble(TextField1.getText().trim());
                double Margen =  Double.parseDouble(TextField2.getText().trim());
                int Iteraciones = Integer.parseInt(TextField3.getText().trim());    
               
                

                Table.updateUI();
                System.out.println(nrf.raiz(Numero, Margen, Iteraciones));
                 total.setText(Integer.toString( (int)(nrf.getlist3().getLast())));

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
        }}else{Table.removeAll();
               nrf.getlist2().removeAll(nrf.getlist2());
               nrf.getlist3().removeAll(nrf.getlist3());
               nrf.getlist().removeAll(nrf.getlist());
               Table.updateUI() ;}

        }

    }
}


